import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>YATA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <div className="flex flex-col items-center justify-center w-full">
          <h1 className="text-[4rem] pt-16">
            Welcome to{' '}
            <span className="text-[#0070f3]">Yet Another Todo App</span>
          </h1>
        </div>
      </main>
    </div>
  );
}
